# Generated by Django 3.2 on 2023-01-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230127_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorited',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_cart',
            new_name='shopping_carts',
        ),
    ]
