# Generated by Django 3.2 on 2023-01-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230127_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_carts',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
