# Generated by Django 3.2 on 2023-01-16 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(related_name='subscripted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
