# Generated by Django 3.2 on 2023-01-22 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscripted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
