# Generated by Django 3.2 on 2023-01-27 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscripted_by', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
